### PR TITLE
Support for Custom Tags & Extensions2.0

### PR DESCRIPTION
**Pull request by bilalhashmi-dt**

### CODE REVIEW

**Comment by TDyszewski** [comment]
Hi, I'm helping with developing dt-cli and one of the issues is to upload extensions to the tenant as @dlopes7 mentioned in https://github.com/dynatrace-oss/api-client-python/pull/33. As we talked on Slack would be great to add upload function. Maybe something like this could work:
```
def post(self, extension_name: str, extension_version: str, zip_file_path: str):
    """ Post the specified version of the extension 2.0
    :param extension_name: the name of the requested extension 2.0
    :param extension_version: the version of the requested extension 2.0
    :param zip_file_path: path to zipped extension 2.0
    :return: HTTP response
    """
    file = Path(zip_file_path)
    with open(file, "rb") as f:
        self.__http_client.make_request(path=f"{self.ENDPOINT}",
                                           method="POST", files={"file": f})
```

**Comment by bilalhashmi-dt** [comment]
Special thanks to our intern Tomek Dyszewski for sending this snippet for Extensions_POST

**Comment by dlopes7** [comment]
Thanks folks, reviewing now

**Comment by dyladan** [comment]
[CLA assistant check](https://cla.oss.dynalabs.io/dynatrace-oss/api-client-python?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.oss.dynalabs.io/dynatrace-oss/api-client-python?pullRequest=36) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: bilalhashmi-dt<br/>:x: David Lopes<br/><hr/>**David Lopes** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.oss.dynalabs.io/check/dynatrace-oss/api-client-python?pullRequest=36) it.</sub>

**Comment by dlopes7** [comment]
@bilalhashmi-dt in the future please make sure to test all methods before pushing, the post method for custom tags was not working because the body was invalid and also had a wrong return type, the delete method also had a wrong response type.

**Pull request merged**
